# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginW(object):
    def setupUi(self, LoginW):
        LoginW.setObjectName("LoginW")
        LoginW.resize(430, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginW.sizePolicy().hasHeightForWidth())
        LoginW.setSizePolicy(sizePolicy)
        LoginW.setMaximumSize(QtCore.QSize(430, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginW.setWindowIcon(icon)
        LoginW.setIconSize(QtCore.QSize(42, 42))
        self.centralwidget = QtWidgets.QWidget(LoginW)
        self.centralwidget.setObjectName("centralwidget")
        self.Username = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(200, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Username.setFont(font)
        self.Username.setObjectName("Username")
        self.Bg = QtWidgets.QLabel(self.centralwidget)
        self.Bg.setGeometry(QtCore.QRect(-1, -30, 501, 311))
        self.Bg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Bg.setText("")
        self.Bg.setPixmap(QtGui.QPixmap("images/Rat.gif"))
        self.Bg.setObjectName("Bg")
        self.Password = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(200, 90, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Password.setFont(font)
        self.Password.setObjectName("Password")
        self.Submit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Submit_Button.setGeometry(QtCore.QRect(80, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Submit_Button.setFont(font)
        self.Submit_Button.setAutoDefault(False)
        self.Submit_Button.setDefault(False)
        self.Submit_Button.setFlat(False)
        self.Submit_Button.setObjectName("Submit_Button")
        self.Cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.Cancel_button.setGeometry(QtCore.QRect(230, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Cancel_button.setFont(font)
        self.Cancel_button.setAutoDefault(False)
        self.Cancel_button.setDefault(False)
        self.Cancel_button.setFlat(False)
        self.Cancel_button.setObjectName("Cancel_button")
        self.Bg.raise_()
        self.Username.raise_()
        self.Password.raise_()
        self.Submit_Button.raise_()
        self.Cancel_button.raise_()
        LoginW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 430, 21))
        self.menubar.setObjectName("menubar")
        LoginW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginW)
        self.statusbar.setObjectName("statusbar")
        LoginW.setStatusBar(self.statusbar)

        self.retranslateUi(LoginW)
        QtCore.QMetaObject.connectSlotsByName(LoginW)

    def retranslateUi(self, LoginW):
        _translate = QtCore.QCoreApplication.translate
        LoginW.setWindowTitle(_translate("LoginW", "Login"))
        self.Submit_Button.setText(_translate("LoginW", "Submit"))
        self.Cancel_button.setText(_translate("LoginW", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginW = QtWidgets.QMainWindow()
    ui = Ui_LoginW()
    ui.setupUi(LoginW)
    LoginW.show()
    sys.exit(app.exec_())
