# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginW(object):
    def setupUi(self, LoginW):
        LoginW.setObjectName("LoginW")
        LoginW.resize(439, 273)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginW.setWindowIcon(icon)
        LoginW.setIconSize(QtCore.QSize(42, 42))
        self.centralwidget = QtWidgets.QWidget(LoginW)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(230, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(180, 20, 211, 201))
        self.graphicsView.setLineWidth(0)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setForegroundBrush(brush)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.label.raise_()
        self.plainTextEdit.raise_()
        LoginW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 439, 21))
        self.menubar.setObjectName("menubar")
        LoginW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginW)
        self.statusbar.setObjectName("statusbar")
        LoginW.setStatusBar(self.statusbar)

        self.retranslateUi(LoginW)
        QtCore.QMetaObject.connectSlotsByName(LoginW)

    def retranslateUi(self, LoginW):
        _translate = QtCore.QCoreApplication.translate
        LoginW.setWindowTitle(_translate("LoginW", "Login"))
        self.label.setText(_translate("LoginW", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginW = QtWidgets.QMainWindow()
    ui = Ui_LoginW()
    ui.setupUi(LoginW)
    LoginW.show()
    sys.exit(app.exec_())
